name: Metrics

on:
  schedule:
    # Runs every 6 hours (adjust as needed)
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Example configuration
          config: |
            template: classic
            user: chtang-hmc
            base: header, activity, community, repositories, metadata
